name: spark

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  repository_dispatch:
    types: [spark]
jobs:
  spark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: ls -la 
